- name: Build EXE
        run: |
          pyinstaller --onefile --noconsole `
            --hidden-import selenium.webdriver.chrome.webdriver `
            --hidden-import selenium.webdriver.chrome.options `
            --hidden-import selenium.webdriver.chrome.service `
            --hidden-import selenium.webdriver.common.by `
            --hidden-import selenium.webdriver.support.ui `
            --hidden-import selenium.webdriver.support.expected_conditions `
            --hidden-import selenium.webdriver.remote.webdriver `
            --hidden-import selenium.webdriver.remote.remote_connection `
            --name "Dados Basicos AGU" `
            app_dados_basicos.py
